<a href="https://colab.research.google.com/github/Danishzaman-0786/torch_operation/blob/main/torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch as t

In [ ]:
if t.cuda.is_available():
    print("GPUis available! You can use a GPU.")
else:
    print("CPU is available. Using the CPU.")


CPU is available. Using the CPU.


In [ ]:
#creat a zeros tensor by using the torch!
a = t.zeros(2)
a

tensor([0., 0.])

In [ ]:
#2d tensor
a=t.zeros(2,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#creat a ones tensor by using the torch!
#1D_tensor
a=t.ones(2)
a

tensor([1., 1.])

In [ ]:
#2D_tensor
a=t.ones(2,3)
a

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#creat a eigen tensor by using the torch!
#1D_tensor
a=t.eye(2,3)
a

tensor([[1., 0., 0.],
        [0., 1., 0.]])

In [ ]:
0#creat a tensor
#2D_tensor
a=t.tensor(((1,2,3),(4,5,6)))

In [ ]:
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
#1D_tensor
a=t.tensor([1,2,3])

In [ ]:
#operation of tensors
a=t.tensor([1,2,3])
b=t.tensor([4,5,6])


In [ ]:
#multiplication
c=a*b

In [ ]:
c

tensor([ 4, 10, 18])

In [ ]:
#or other method
c=t.mul(a,b)

In [ ]:
c

tensor([ 4, 10, 18])

In [ ]:
#dividing
c=a/b

In [ ]:
c

tensor([0.2500, 0.4000, 0.5000])

In [ ]:
#other method for dividing
c=t.divide(a,b)

In [ ]:
c

tensor([0.2500, 0.4000, 0.5000])

In [ ]:
#addition
c=a+b

In [ ]:
c

tensor([5, 7, 9])

In [ ]:
#other method fpor addition
c=t.add(a,b)

In [ ]:
c

tensor([5, 7, 9])

In [ ]:
#subtraction
c=a-b

In [ ]:
c

tensor([-3, -3, -3])

In [ ]:
#other method for subtraction
c=t.sub(a,b)

In [ ]:
c

tensor([-3, -3, -3])

In [ ]:
print(a,b,end=' ')

tensor([1, 2, 3]) tensor([4, 5, 6]) 

In [ ]:
t.tensor((1,2,3),dtype=t.float )

tensor([1., 2., 3.])

In [ ]:
#creat a empty tensor
#1D_tensor
a=t.empty(2)

In [ ]:
a

tensor([2.9669e-32, 4.4001e-41])

In [ ]:
#2D_tensor_for empty
a=t.empty(2,3)

In [ ]:
a

tensor([[2.9669e-32, 4.4001e-41, 5.5430e-36],
        [3.2436e-41, 4.4842e-44, 0.0000e+00]])

In [ ]:
#random variable for tensor
#1D_tensor
a=t.rand(2)#range[0-1]


In [ ]:
a

tensor([0.1054, 0.5835])

In [ ]:
a=t.randn(2)

In [ ]:
a

tensor([-0.0298,  0.8855])

In [ ]:
#using the seed for stop the random variable
t.manual_seed(0)
a=t.rand(2)

In [ ]:
a

tensor([0.4963, 0.7682])

In [ ]:
#full tensor
a=t.full((2,3),4)

In [ ]:
a

tensor([[4, 4, 4],
        [4, 4, 4]])

In [ ]:
#linspace tensor
a=t.linspace(0,10,steps=5)

In [ ]:
a

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [ ]:
#arrange tensor
a=t.arange(0,10,1)

In [ ]:
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#arrange
a=t.arange(2)

In [ ]:
a

tensor([0, 1])

In [ ]:
#arrange
a=t.arange(2,10)

In [ ]:
a

tensor([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#now we statrt the how to calculate the shape of tensor
a=t.tensor([1,2,3])


In [ ]:
a.shape

torch.Size([3])

In [ ]:
a.shape[0]

3

In [ ]:
a.size()

torch.Size([3])

In [ ]:
#for 2D array
a=t.tensor([[1,2,3],[4,5,6]])

In [ ]:
a.shape

torch.Size([2, 3])

In [ ]:
a=t.tensor((1,2,3,4,5))

In [ ]:
a

tensor([1, 2, 3, 4, 5])

In [ ]:
t.clamp(a,min=1, max=3)

tensor([1, 2, 3, 3, 3])

In [ ]:
#calculate the sum
a=t.tensor([1,2,3])

In [ ]:
a.sum()

tensor(6)

In [ ]:
t.sum(a)

tensor(6)

In [ ]:
a.max()

tensor(3)

In [ ]:
t.max(a)

tensor(3)

In [ ]:
a.min()

tensor(1)

In [ ]:
t.min(a)

tensor(1)

In [ ]:
t.sqrt(a)

tensor([1.0000, 1.4142, 1.7321])

In [ ]:
a.sqrt()

tensor([1.0000, 1.4142, 1.7321])

In [ ]:
#sum for 2D tensor
a=t.tensor([[1,2,3],[4,5,6]])

In [ ]:
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
t.sum(a,dim=0)

tensor([5, 7, 9])

In [ ]:
#1D
t.sum(a,dim=1)

tensor([ 6, 15])

In [ ]:
#2D
t.sum(a,dim=0)

tensor([5, 7, 9])

In [ ]:
t.sum(a,dim=0)

tensor([5, 7, 9])

In [ ]:
#rows=1,column=0....dim=0, dim=1
t.sum(a,dim=1)#row wise sum

tensor([ 6, 15])

In [ ]:
t.sum(a,dim=0)#column wise sum

tensor([5, 7, 9])

In [ ]:
a=t.tensor([1,2,3],dtype=t.float)

In [ ]:
a.type()

'torch.FloatTensor'

In [ ]:
t.mean(a)

tensor(2.)

In [ ]:
#we findout the mean from column and row
a=t.tensor([[1,2,3],[4,5,6]],dtype=t.float)

In [ ]:
a

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
#row wise dim=1
t.mean(a,dim=1)

tensor([2., 5.])

In [ ]:
#column wise
t.mean(a,dim=0)

tensor([2.5000, 3.5000, 4.5000])

In [ ]:
#column wise min,max findout
t.min(a,dim=0)

torch.return_types.min(
values=tensor([1., 2., 3.]),
indices=tensor([0, 0, 0]))

In [ ]:
#row wise min
t.min(a,dim=1)

torch.return_types.min(
values=tensor([1., 4.]),
indices=tensor([0, 0]))

In [ ]:
# we calculate the median
a=t.tensor([1,2,3],dtype=t.float)

In [ ]:
t.median(a)

tensor(2.)

In [ ]:
#calculate the product
a=t.tensor([1,2,3])

In [ ]:
t.prod(a)

tensor(6)

In [ ]:
a=t.tensor([[1,2,3],[4,5,6]])

In [ ]:
t.prod(a)

tensor(720)

In [ ]:
#column Wise product
t.prod(a,dim=0)

tensor([ 4, 10, 18])

In [ ]:
#row Wise product
t.prod(a,dim=1)

tensor([  6, 120])

In [ ]:
#we calculate the standar ddeviation
a=t.tensor([1,2,3],dtype=t.float)


In [ ]:
a

tensor([1., 2., 3.])

In [ ]:
t.std(a)

tensor(1.)

In [ ]:
a.std()

tensor(1.)

In [ ]:
a=t.tensor([[1,2,3],[4,5,6]],dtype=t.float)

In [ ]:
a

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
#column Wise std
t.std(a,dim=0)

tensor([2.1213, 2.1213, 2.1213])

In [ ]:
#rows Wise
t.std(a,dim=1)

tensor([1., 1.])

In [ ]:
#variance
a=t.tensor([1,2,3],dtype=t.float)

In [ ]:
t.var(a)

tensor(1.)

In [ ]:
a=t.tensor([[1,2,3],[4,5,6]],dtype=t.float)

In [ ]:
a

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
#column Wise variance
t.var(a,dim=0)

tensor([4.5000, 4.5000, 4.5000])

In [ ]:
#row Wise variance
t.var(a,dim=1)

tensor([1., 1.])

In [ ]:
a=t.tensor([10,200,30],dtype=t.float)

In [ ]:
a

tensor([ 10., 200.,  30.])

In [ ]:
#argmax_denoted a in
t.argmax(a)


tensor(1)